version: '3'
services:

  database:
    image: library/mysql:latest
    restart: always
    container_name: database
    volumes:
      - './docker/db/data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registro-calcio
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
    - 55500:3306

  registro-calcio-backend:
    build: ./backend
    container_name: registro-calcio-backend
    ports:
      - 55501:8080
    restart: always
    depends_on:
      - database

  registro-calcio-frontend:
    build: ./frontend/rc-fe-ng
    container_name: registro-calcio-frontend
    ports:
      - 55502:80
    depends_on:
      - registro-calcio-backend
    restart: always