spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/registro_calcio?serverTimezone=UTC
#    username: root
#    password: root
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net:3306/heroku_0f0df99008ebf36?serverTimezone=UTC
    username: b78234b97a67d1
    password: 2e7441de

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  error:
    include-message: always