#Database credentials for docker
spring:
  datasource:
    jdbcUrl: jdbc:mysql://database:3306/registro-calcio?serverTimezone=UTC
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver