#Project settings
spring:
  second-datasource:
      jdbcUrl: jdbc:hsqldb:mem:active_sessions
      driverClassName: org.hsqldb.jdbc.JDBCDriver
      username: token
      password: token
      ddl-auto: create
      dialect: org.hibernate.dialect.HSQLDialect
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/registro_calcio?serverTimezone=UTC
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    generate-ddl: true
    show-sql: true
  mail:
    properties.mail.smtp:
      ssl.enable: true
      auth: true
      starttls.enable: true
    host: smtp.yandex.com
    port: 465
    password: ckuootdujblrjrxa
    username: registro.calcio.elis@yandex.com

server:
  error:
    include-message: always

logging:
  level:
    org.springframework: WARN
    com.appicantion.name: INFO
  file:
    name: logs/registro-calcio.log
    max-size: 10MB

