spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registro_calcio?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  error:
    include-message: always

java:
  runtime:
    version: 11