version: '3'
services:

  database:
    image: library/mysql:latest
    restart: always
    container_name: database
    volumes:
      - './docker/db/data:/var/lib/prod/mysql'
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: registro_calcio
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 55500:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+01:00']

  registro-calcio-backend:
    build: ../
    container_name: registro-calcio-backend
    ports:
      - 8080:8080
    volumes:
      - '../logs:/logs'
    restart: always
    depends_on:
      - database

  registro-calcio-frontend-prime:
    build: ../../rc-fe-prime-ng
    container_name: registro-calcio-frontend-prime
    ports:
      - 81:4200
    depends_on:
      - registro-calcio-backend
    restart: always