version: '3'
services:

  database-dev:
    image: library/mysql:latest
    restart: always
    container_name: database-dev
    volumes:
      - './docker/db/data:/var/lib/prod/mysql'
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: registro_calcio
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 55501:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+01:00']

  registro-calcio-backend-dev:
    build: ../
    container_name: registro_calcio_backend-dev
    ports:
      - 8085:8080
    volumes:
      - '../logs:/logs'
    restart: always
    depends_on:
      - database-dev

  registro-calcio-frontend-prime-dev:
    build: ../../rc-fe-prime-ng-dev
    container_name: registro-calcio-frontend-prime-dev
    ports:
      - 82:80
    depends_on:
      - registro-calcio-backend-dev
    links:
      - registro-calcio-backend-dev