version: '3'
services:

  database:
#    image: library/mysql:latest
    build: mysql
    restart: always
    container_name: database
    volumes:
      - './docker/db/data:/var/lib/prod/mysql'
    environment:
      TZ: UTC
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registro_calcio
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 55500:3306

  registro-calcio-backend:
    build: ../
    container_name: registro-calcio-backend
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database

  registro-calcio-frontend-prime:
    build: ../../rc-fe-prime-ng
    container_name: registro-calcio-frontend-prime
    ports:
      - 80:4200
    depends_on:
      - registro-calcio-backend
    restart: always