version: '3'
services:

  database-testing:
    image: library/mysql:latest
    restart: always
    container_name: database-testing
    volumes:
      - './docker/db/data:/var/lib/test/mysql'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registro_calcio_testing
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 55501:3306

  registro-calcio-backend-security:
    build: ../
    container_name: registro-calcio-backend-security
    ports:
      - 55505:8080
    restart: always
    depends_on:
      - database-testing

#  registro-calcio-frontend:
#    build: ../../rc-fe-ng
#    container_name: registro-calcio-frontend
#    ports:
#      - 80:80
#    depends_on:
#      - registro-calcio-backend-security
#    restart: always