package com.elis.registrocalcio.enumPackage;

public enum FootballRegisterException {
        CANNOT_REMOVE_BINDING,
        CANNOT_DELETE_PLAYED_EVENTS,
        WRONG_DATE_FORMAT,
        WRONG_PLAYERS_ERROR,
        WRONG_TEAM_SIZE,
        AUTHENTICATION_FAILED,
        CANNOT_CHANGE_USER_ROLE,
        INVALID_TOKEN,
        CANNOT_REGISTER_USER,
        EVENT_ALREADY_EXIST_IN_THE_GIVEN_DAY,
        EVENT_NOT_FOUND,
        USER_NOT_FOUND,
        PERMISSION_DENIED,
        EMAIL_ALREADY_EXIST,
        INVALID_REGISTRATION_FIELDS,
        INVALID_LOGIN_FIELDS,
        OVERLAPPING_EVENTS
}
